### PR TITLE
Fixing Oraqles UI

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
Fixing Oraqles UI

Changes:

Reduced hydration errors to 4.
Fixes mobile menu.
Fixing dark mode toggle.

### CODE REVIEW

**Comment by Adebesin-Cell** [comment]
@Emmanueldmlr Should I open this PR and you review it? It's becoming a large one.

**Comment by Emmanueldmlr** [comment]
Yes

**Comment by Emmanueldmlr** [comment]
@Adebesin-Cell , kindly reduce the size of the public/favicon.png icon...274kb is really much.

**Review by Simplypheyie96 — APPROVED** [review]
The homepage looks good! We just need the new banner now

**Review by Simplypheyie96 — APPROVED** [review]
The homepage looks good! We just need the new banner now

**Review by Simplypheyie96 — APPROVED** [review]
.

**Review by Emmanueldmlr — APPROVED** [review]

**Pull request merged**
